apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave-1
  namespace: jenkins
  labels:
    app: jenkins-slave-1
spec:
  ports:
  - port: 8080
    name: jenkins-port-1
  - port: 50000
    name: jnlp-port-1
  clusterIP: None
  selector:
    app: jenkins-slave-1
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave-2
  namespace: jenkins
  labels:
    app: jenkins-slave-2
spec:
  ports:
  - port: 8080
    name: jenkins-port-2
  - port: 50000
    name: jnlp-port-2
  clusterIP: None
  selector:
    app: jenkins-slave-2