apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  serviceName: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        kubernetes.io/hostname: node6
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins
          image: jenkinsci/jenkins:2.150.1
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: docker
              mountPath: /usr/bin/docker
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: docker-lib
              mountPath: /usr/lib/x86_64-linux-gnu/libltdl.so.7
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: resolve
              mountPath: /etc/resolv.conf
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-master-pvc
        - name: docker
          hostPath:
            path: /usr/bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libltdl.so.7
        - name: resolve
          hostPath:
            path: /etc/resolv.conf