apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - port: 8080
    name: jenkins-port
  - port: 50000
    name: jnlp-port
  clusterIP: None
  selector:
    app: jenkins