apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
spec:
  storageClassName: jenkins-master
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube/data/jenkinsmaster/pv

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-master-pvc
  namespace: jenkins
spec:
  storageClassName: jenkins-master
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
