apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-slave-pv1
spec:
  storageClassName: jenkins-slave-1
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube/data/jenkinsslave/pv1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-slave-pv2
spec:
  storageClassName: jenkins-slave-2
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube/data/jenkinsslave/pv2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-slave-pvc1
  namespace: jenkins
spec:
  storageClassName: jenkins-slave-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-slave-pvc2
  namespace: jenkins
spec:
  storageClassName: jenkins-slave-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi